whens: whens.cpp ../task.hpp ../io_service.hpp ../promise.hpp ../when.hpp ../cancelable.hpp
	clang++ -std=c++17 -g -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -luring /home/carter/fmt/src/format.cc ./whens.cpp -I.. -o whens -O0 -D_LIBCPP_DEBUG_LEVEL=1 -Wall -fno-omit-frame-pointer -fsanitize=address
