whens: whens.cpp ../global.cpp ../task.hpp ../async_coro.hpp ../promise.hpp ../when.hpp
	clang++ -std=c++17 -g -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -luring -lfmt ./whens.cpp ../global.cpp -I.. -o whens -O0 -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address
